name: ukk
description: "Aplikasi Peminjaman Alat Teknik Pembangkit"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core & Backend
  supabase_flutter: ^2.3.4

  # State Management
  flutter_riverpod: ^2.5.1

  # UI & Utility
  intl: ^0.19.0
  google_fonts: ^8.0.0
  fluttertoast: ^8.2.8
  flutter_spinkit: ^5.2.1
  cached_network_image: ^3.4.0

  # PDF & Printing
  printing: ^5.12.0
  pdf: ^3.11.0

  # Navigasi (direkomendasikan)
  go_router: ^14.2.7

  # File & Path
  path_provider: ^2.1.5
  file_picker: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/   # ini akan ambil semua gambar di folder assets/ (paling aman)

  # fonts: (opsional, kalau pakai google_fonts sudah cukup)
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: fonts/Poppins-Regular.ttf
  #       - asset: fonts/Poppins-Bold.ttf
  #         weight: 700